name: Release

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: 'Release version (<MAJOR>.<MINOR>)'
        required: true

permissions:
  contents: write

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TAG: v${{ inputs.release-version }}
      WINDOWS_RELEASE_PLUGIN_ZIP: navme-cli_windows_v${{ inputs.release-version }}.zip

    steps:
      - uses: actions/checkout@v3

      - name: Download built plugin (Windows)
        uses: actions/download-artifact@v3
        with:
          name: built-application-windows 
          path: built-application-windows/x64/Release/

      - name: Copy config file
        run: |
          cp navme-cli.ini built-application-windows/

      - name: Copy html template
        run: |
          mkdir built-application-windows/html-report-template
          cp html-report-template/flight_plan_template.html built-application-windows/html-report-template/

      - name: Create export directory
        run: |
          mkdir built-application-windows/export
      
      - name: Create release plugin zip (Windows)
        run: |
          cd built-application-windows
          zip -r ../${WINDOWS_RELEASE_PLUGIN_ZIP} .

      - name: Create draft release
        run: |
          gh release create \
            --draft \
            --title "v${{ inputs.release-version }} release" \
            --generate-notes \
            ${TAG} \
            ${WINDOWS_RELEASE_PLUGIN_ZIP}
